### ISSUE TITLE
[Bug} Game crashes when cosmetics are equipped

### ISSUE THREAD

**Issue by VHSGirl** [WhoCraft/WhoCosmetics#10] opened 2023-12-20 18:06 UTC
I have several other mods installed so I understand if it's a compatibility issue but I wanted to share my problem.
The game crashes and will not let me rejoin my world if an item from the mod is equipped. The same goes if it is equipped on to an armour stand. 

Below is the error message.

The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class mc.craig.software.cosmetics.common.items.ClothingItem cannot be cast to class mc.craig.software.regen.common.item.ICustomArmorTexture (mc.craig.software.cosmetics.common.items.ClothingItem and mc.craig.software.regen.common.item.ICustomArmorTexture are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3bbc39f8)

thanks!

**Comment by Jeryn99** [comment] 2023-12-20 20:01
Hey it's probably about time I fixed this, it's a incompatibility between two of my mods that I keep putting off sorting 

1.19?

**Comment by VHSGirl** [comment] 2023-12-20 21:22
Yeah I'm running 1.19, does it matter which forge version I'm using?

**Comment by Jeryn99** [comment] 2024-08-11 11:12
Duplicate of https://github.com/Jeryn99/WhoCosmetics/issues/12

**Closed as completed by Jeryn99** 2024-08-11 11:12 UTC
