### ISSUE TITLE
Adding other mods will crash when wearing gear

### ISSUE THREAD

**Issue by smallmoss233** [WhoCraft/WhoCosmetics#14] opened 2024-07-05 02:59 UTC
Adding other mods will crash when wearing gear
Error reporting：
    WhoCosmetics
    Regeneration
    Konkrete

**Comment by Jeryn99** [comment] 2024-08-11 11:13
Duplicate of https://github.com/Jeryn99/WhoCosmetics/issues/12

**Closed as completed by Jeryn99** 2024-08-11 11:13 UTC
